# Mail Generating using Py from Outlook

# Install -> pip install pywin32

import win32com.client

def send_email(to, subject, body, attachment=None, html_body=None):
    try:
        outlook = win32com.client.Dispatch("Outlook.Application")
        mail = outlook.CreateItem(0)  # 0 represents a MailItem object
        
        # Set email properties
        mail.To = to
        mail.Subject = subject
        # mail.Cc= XXXX

        if html_body:
            mail.HTMLBody = html_body
        else:
            mail.Body = body

        if attachment:
            mail.Attachments.Add(attachment)

        # Send the email
        mail.Send()
        print("Email sent successfully!")

    except Exception as e:
        print(f"An error occurred: {e}")
        

# Replace these values with the recipient's email address, subject, and body
to_email = "your_to_mail@mgmail.com"
email_subject = "Hello, this autogenerated mail "
email_body = "This is a test email sent from Python."

# Attachments=r"C:\Users\003LGU744\Downloads\dummy.txt"

# Call the function to send the email
send_email(to_email, email_subject, email_body)

    
